/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiass2antoinettebolger;

import java.awt.EventQueue;
import java.beans.Beans;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import java.util.*;
import java.util.regex.*;
import java.sql.*;
import static javax.management.Query.value;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import static org.eclipse.persistence.internal.jpa.parsing.jpql.antlr.JPQLLexer.SUM;

/**
 *
 * @author Antoinette M. bolger
 */
public class NewMasterDetailForm extends JPanel {



    

   
    
    public NewMasterDetailForm() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("shopPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Products p");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        productsQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Products p");
        productsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productsQuery.getResultList();
        productsQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Products p");
        productsList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productsQuery1.getResultList();
        productsQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Products p");
        productsList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productsQuery2.getResultList();
        productsQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Products p");
        productsList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productsQuery3.getResultList();
        tpass2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        dataBase = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        logoutMenu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        productidLabel = new javax.swing.JLabel();
        productnameLabel = new javax.swing.JLabel();
        supplieridLabel = new javax.swing.JLabel();
        categoryidLabel = new javax.swing.JLabel();
        quantyLabel = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        productnameField = new javax.swing.JTextField();
        supplieridField = new javax.swing.JTextField();
        categoryidField = new javax.swing.JTextField();
        quantyField = new javax.swing.JTextField();
        unitField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();
        saveButton1 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        menuHelp1 = new javax.swing.JButton();
        logoutHelp1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        supplieridLabel2 = new javax.swing.JLabel();
        supplieridLabel3 = new javax.swing.JLabel();
        supplyQuanty = new javax.swing.JTextField();
        Supplierrid = new javax.swing.JTextField();
        supplieridLabel4 = new javax.swing.JLabel();
        Supplierrid1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        menuHelp2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        email = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        emailbtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        logoutHelp = new javax.swing.JButton();
        menuHelp = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(730, 530));
        setMinimumSize(new java.awt.Dimension(730, 530));
        setPreferredSize(new java.awt.Dimension(730, 530));
        setRequestFocusEnabled(false);

        tpass2.setBackground(new java.awt.Color(0, 0, 0));
        tpass2.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        tpass2.setMaximumSize(new java.awt.Dimension(720, 330));
        tpass2.setMinimumSize(new java.awt.Dimension(720, 330));
        tpass2.setPreferredSize(new java.awt.Dimension(720, 330));

        jPanel1.setBackground(new java.awt.Color(219, 219, 219));
        jPanel1.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(620, 330));
        jPanel1.setMinimumSize(new java.awt.Dimension(620, 330));
        jPanel1.setPreferredSize(new java.awt.Dimension(620, 330));

        jPanel5.setBackground(new java.awt.Color(219, 219, 219));
        jPanel5.setMaximumSize(new java.awt.Dimension(350, 330));
        jPanel5.setMinimumSize(new java.awt.Dimension(350, 330));
        jPanel5.setPreferredSize(new java.awt.Dimension(350, 330));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiass2antoinettebolger/menu page.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiass2antoinettebolger/menu food.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        dataBase.setBackground(new java.awt.Color(14, 13, 13));
        dataBase.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        dataBase.setForeground(new java.awt.Color(255, 255, 255));
        dataBase.setText("Inventory");
        dataBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        dataBase.setPreferredSize(new java.awt.Dimension(150, 40));
        dataBase.addActionListener(formListener);

        jButton2.setBackground(new java.awt.Color(14, 13, 13));
        jButton2.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("K.P.I.");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.setPreferredSize(new java.awt.Dimension(150, 40));
        jButton2.addActionListener(formListener);

        jButton3.setBackground(new java.awt.Color(14, 13, 13));
        jButton3.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Help");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton3.setPreferredSize(new java.awt.Dimension(150, 40));
        jButton3.addActionListener(formListener);

        logoutMenu.setBackground(new java.awt.Color(14, 13, 13));
        logoutMenu.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        logoutMenu.setForeground(new java.awt.Color(255, 255, 255));
        logoutMenu.setText("Logout");
        logoutMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        logoutMenu.setPreferredSize(new java.awt.Dimension(150, 40));
        logoutMenu.addActionListener(formListener);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataBase, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(dataBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(logoutMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jLabel7.setFont(new java.awt.Font("Bell MT", 2, 24)); // NOI18N
        jLabel7.setText("WOODEN SPOON FOODS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpass2.addTab("Menu", null, jPanel1, "");

        jPanel2.setBackground(new java.awt.Color(219, 219, 219));
        jPanel2.setMaximumSize(new java.awt.Dimension(620, 330));
        jPanel2.setMinimumSize(new java.awt.Dimension(620, 330));
        jPanel2.setPreferredSize(new java.awt.Dimension(620, 330));

        masterTable.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productid}"));
        columnBinding.setColumnName("Productid");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${productname}"));
        columnBinding.setColumnName("Productname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${supplierid}"));
        columnBinding.setColumnName("Supplierid");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${categoryid}"));
        columnBinding.setColumnName("Categoryid");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${quanty}"));
        columnBinding.setColumnName("Quanty");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${unit}"));
        columnBinding.setColumnName("Unit");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${price}"));
        columnBinding.setColumnName("Price");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);

        masterScrollPane.setViewportView(masterTable);

        productidLabel.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        productidLabel.setText("Productid:");

        productnameLabel.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        productnameLabel.setText("Productname:");

        supplieridLabel.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        supplieridLabel.setText("Supplierid:");

        categoryidLabel.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        categoryidLabel.setText("Categoryid:");

        quantyLabel.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        quantyLabel.setText("Quanty:");

        unitLabel.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        unitLabel.setText("Unit:");

        priceLabel.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        priceLabel.setText("Price:");

        productnameField.setBackground(new java.awt.Color(219, 219, 219));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.productname}"), productnameField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), productnameField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        supplieridField.setBackground(new java.awt.Color(219, 219, 219));
        supplieridField.setToolTipText("numbers only");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.supplierid}"), supplieridField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), supplieridField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        categoryidField.setBackground(new java.awt.Color(219, 219, 219));
        categoryidField.setToolTipText("numbers only");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.categoryid}"), categoryidField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), categoryidField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        quantyField.setBackground(new java.awt.Color(219, 219, 219));
        quantyField.setToolTipText("numbers only");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.quanty}"), quantyField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), quantyField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        unitField.setBackground(new java.awt.Color(219, 219, 219));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.unit}"), unitField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), unitField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        priceField.setBackground(new java.awt.Color(219, 219, 219));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.price}"), priceField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), priceField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        saveButton.setBackground(new java.awt.Color(219, 219, 219));
        saveButton.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(formListener);

        refreshButton.setBackground(new java.awt.Color(219, 219, 219));
        refreshButton.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(formListener);

        newButton.setBackground(new java.awt.Color(219, 219, 219));
        newButton.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        newButton.setText("New");
        newButton.addActionListener(formListener);

        deleteButton.setBackground(new java.awt.Color(219, 219, 219));
        deleteButton.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        deleteButton.setText("Delete");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        deleteButton.addActionListener(formListener);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiass2antoinettebolger/table page.png"))); // NOI18N

        menuButton.setBackground(new java.awt.Color(219, 219, 219));
        menuButton.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        menuButton.setText("Menu");
        menuButton.addActionListener(formListener);

        saveButton1.setBackground(new java.awt.Color(219, 219, 219));
        saveButton1.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        saveButton1.setText("Logout");
        saveButton1.addActionListener(formListener);

        jSlider1.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jSlider1.setForeground(new java.awt.Color(0, 0, 0));
        jSlider1.setMajorTickSpacing(10);
        jSlider1.setMaximum(50);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.productid}"), jSlider1, org.jdesktop.beansbinding.BeanProperty.create("value"));
        binding.setSourceNullValue(1);
        binding.setSourceUnreadableValue(1);
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(newButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productnameLabel)
                            .addComponent(supplieridLabel)
                            .addComponent(categoryidLabel)
                            .addComponent(quantyLabel)
                            .addComponent(unitLabel)
                            .addComponent(priceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productnameField)
                            .addComponent(supplieridField)
                            .addComponent(categoryidField)
                            .addComponent(quantyField)
                            .addComponent(unitField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(priceField)
                            .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(productidLabel)
                    .addContainerGap(616, Short.MAX_VALUE)))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteButton, newButton, refreshButton, saveButton});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productnameLabel)
                            .addComponent(productnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supplieridLabel)
                            .addComponent(supplieridField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoryidLabel)
                            .addComponent(categoryidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantyLabel)
                            .addComponent(quantyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unitLabel)
                            .addComponent(unitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceLabel)
                            .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(refreshButton)
                    .addComponent(deleteButton)
                    .addComponent(newButton)
                    .addComponent(menuButton)
                    .addComponent(saveButton1))
                .addGap(9, 9, 9))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(218, Short.MAX_VALUE)
                    .addComponent(productidLabel)
                    .addGap(264, 264, 264)))
        );

        tpass2.addTab("Inventory", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(620, 330));
        jPanel3.setMinimumSize(new java.awt.Dimension(620, 330));
        jPanel3.setPreferredSize(new java.awt.Dimension(620, 330));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiass2antoinettebolger/statics.png"))); // NOI18N

        menuHelp1.setBackground(new java.awt.Color(14, 13, 13));
        menuHelp1.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        menuHelp1.setForeground(new java.awt.Color(255, 255, 255));
        menuHelp1.setText("Menu");
        menuHelp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        menuHelp1.setPreferredSize(new java.awt.Dimension(150, 40));
        menuHelp1.addActionListener(formListener);

        logoutHelp1.setBackground(new java.awt.Color(14, 13, 13));
        logoutHelp1.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        logoutHelp1.setForeground(new java.awt.Color(255, 255, 255));
        logoutHelp1.setText("Logout");
        logoutHelp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        logoutHelp1.setPreferredSize(new java.awt.Dimension(150, 40));
        logoutHelp1.addActionListener(formListener);

        jPanel8.setBackground(new java.awt.Color(219, 219, 219));

        supplieridLabel2.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        supplieridLabel2.setText("Quanty of units in stock");

        supplieridLabel3.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        supplieridLabel3.setText("Value of units in stock");

        supplyQuanty.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        supplyQuanty.setEnabled(false);
        supplyQuanty.addActionListener(formListener);

        Supplierrid.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        Supplierrid.setEnabled(false);

        supplieridLabel4.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        supplieridLabel4.setText("Total Value of  stock");

        Supplierrid1.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        Supplierrid1.setEnabled(false);

        jButton1.setBackground(new java.awt.Color(14, 13, 13));
        jButton1.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update K.P.I.s");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(formListener);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplieridLabel4)
                            .addComponent(supplieridLabel2)
                            .addComponent(supplieridLabel3))
                        .addGap(108, 108, 108)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(supplyQuanty, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Supplierrid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Supplierrid1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supplieridLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(supplyQuanty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Supplierrid1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplieridLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Supplierrid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplieridLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(60, 60, 60)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuHelp2.setBackground(new java.awt.Color(14, 13, 13));
        menuHelp2.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        menuHelp2.setForeground(new java.awt.Color(255, 255, 255));
        menuHelp2.setText("Clear");
        menuHelp2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        menuHelp2.setPreferredSize(new java.awt.Dimension(150, 40));
        menuHelp2.addActionListener(formListener);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(menuHelp2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(menuHelp1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logoutHelp1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menuHelp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutHelp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuHelp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
        );

        tpass2.addTab("K.P.I", jPanel3);

        jPanel4.setBackground(new java.awt.Color(219, 219, 219));
        jPanel4.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jPanel4.setMaximumSize(new java.awt.Dimension(620, 330));
        jPanel4.setMinimumSize(new java.awt.Dimension(620, 330));
        jPanel4.setPreferredSize(new java.awt.Dimension(620, 330));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiass2antoinettebolger/help menu.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(219, 219, 219));
        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel6.setText("HOW CAN WE HELP");

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N

        message.setColumns(20);
        message.setRows(5);
        jScrollPane2.setViewportView(message);

        emailbtn.setBackground(new java.awt.Color(219, 219, 219));
        emailbtn.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        emailbtn.setText("Send Email");
        emailbtn.addActionListener(formListener);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("YOUR MESSAGE");

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(" EMAIL");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(emailbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        logoutHelp.setBackground(new java.awt.Color(14, 13, 13));
        logoutHelp.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        logoutHelp.setForeground(new java.awt.Color(255, 255, 255));
        logoutHelp.setText("Logout");
        logoutHelp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        logoutHelp.setPreferredSize(new java.awt.Dimension(150, 40));
        logoutHelp.addActionListener(formListener);

        menuHelp.setBackground(new java.awt.Color(14, 13, 13));
        menuHelp.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        menuHelp.setForeground(new java.awt.Color(255, 255, 255));
        menuHelp.setText("Menu");
        menuHelp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        menuHelp.setPreferredSize(new java.awt.Dimension(150, 40));
        menuHelp.addActionListener(formListener);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(menuHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tpass2.addTab("Help", jPanel4);
        jPanel4.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpass2, javax.swing.GroupLayout.PREFERRED_SIZE, 705, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpass2, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tpass2.getAccessibleContext().setAccessibleName("Menu");

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == dataBase) {
                NewMasterDetailForm.this.dataBaseActionPerformed(evt);
            }
            else if (evt.getSource() == jButton2) {
                NewMasterDetailForm.this.jButton2ActionPerformed(evt);
            }
            else if (evt.getSource() == jButton3) {
                NewMasterDetailForm.this.jButton3ActionPerformed(evt);
            }
            else if (evt.getSource() == logoutMenu) {
                NewMasterDetailForm.this.logoutMenuActionPerformed(evt);
            }
            else if (evt.getSource() == saveButton) {
                NewMasterDetailForm.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton) {
                NewMasterDetailForm.this.refreshButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newButton) {
                NewMasterDetailForm.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == deleteButton) {
                NewMasterDetailForm.this.deleteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == menuButton) {
                NewMasterDetailForm.this.menuButtonActionPerformed(evt);
            }
            else if (evt.getSource() == saveButton1) {
                NewMasterDetailForm.this.saveButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == menuHelp1) {
                NewMasterDetailForm.this.menuHelp1ActionPerformed(evt);
            }
            else if (evt.getSource() == logoutHelp1) {
                NewMasterDetailForm.this.logoutHelp1ActionPerformed(evt);
            }
            else if (evt.getSource() == supplyQuanty) {
                NewMasterDetailForm.this.supplyQuantyActionPerformed(evt);
            }
            else if (evt.getSource() == jButton1) {
                NewMasterDetailForm.this.jButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == menuHelp2) {
                NewMasterDetailForm.this.menuHelp2ActionPerformed(evt);
            }
            else if (evt.getSource() == emailbtn) {
                NewMasterDetailForm.this.emailbtnActionPerformed(evt);
            }
            else if (evt.getSource() == logoutHelp) {
                NewMasterDetailForm.this.logoutHelpActionPerformed(evt);
            }
            else if (evt.getSource() == menuHelp) {
                NewMasterDetailForm.this.menuHelpActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void menuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelpActionPerformed
        tpass2.setSelectedIndex(0);// TODO add your handling code here:
    }//GEN-LAST:event_menuHelpActionPerformed

    private void logoutHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutHelpActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_logoutHelpActionPerformed

    private void emailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailbtnActionPerformed

        String email1 = email.getText();
        String regEx = "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}\\b";

        Pattern p = Pattern.compile(regEx);
        Matcher m = p.matcher(email1);

        if(m.find())
        {
            JOptionPane.showMessageDialog(null, "Valid Email address: Email Sent");

            email.setText("");
            message.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Invalid Email address: Email Not Sent");
        }
    }//GEN-LAST:event_emailbtnActionPerformed

    private void supplyQuantyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplyQuantyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplyQuantyActionPerformed

    private void logoutHelp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutHelp1ActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_logoutHelp1ActionPerformed

    private void menuHelp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelp1ActionPerformed
        tpass2.setSelectedIndex(0);// TODO add your handling code here:
    }//GEN-LAST:event_menuHelp1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
            
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/shop", "anto", "1111" );
             DatabaseMetaData dbMetaData = con.getMetaData();
 
      Statement stmt = con.createStatement();
      ResultSet rs = stmt.executeQuery("SELECT * FROM ANTO.PRODUCTS ");
      
      
      while (rs.next()) {
          
                int sum = rs.getInt("QUANTY");
                int price = rs.getInt("PRICE");
                int surply =(sum*price);
                
               
           supplyQuanty.setText(String.valueOf(sum));
           Supplierrid1.setText(String.valueOf(price));
           Supplierrid.setText(String.valueOf(surply));
               
           
           
      }

          

        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "No K.P.I.'s Available"+e);
        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_saveButton1ActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        tpass2.setSelectedIndex(0);// TODO add your handling code here:
    }//GEN-LAST:event_menuButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int[] selected = masterTable.getSelectedRows();
        List<guiass2antoinettebolger.Products> toRemove = new ArrayList<guiass2antoinettebolger.Products>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            guiass2antoinettebolger.Products p = list.get(masterTable.convertRowIndexToModel(selected[idx]));
            toRemove.add(p);
            entityManager.remove(p);
        }
        list.removeAll(toRemove);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        try{  guiass2antoinettebolger.Products p = new guiass2antoinettebolger.Products();
            entityManager.persist(p);
            list.add(p);
            int row = list.size() - 1;
            masterTable.setRowSelectionInterval(row, row);
            masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "error"+e);
        }
    }//GEN-LAST:event_newButtonActionPerformed

    @SuppressWarnings("unchecked")
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<guiass2antoinettebolger.Products> merged = new ArrayList<guiass2antoinettebolger.Products>(list.size());
            for (guiass2antoinettebolger.Products p : list) {
                merged.add(entityManager.merge(p));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void logoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_logoutMenuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tpass2.setSelectedIndex(3);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tpass2.setSelectedIndex(2);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dataBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataBaseActionPerformed
        tpass2.setSelectedIndex(1);// TODO add your handling code here:

    }//GEN-LAST:event_dataBaseActionPerformed

    private void menuHelp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelp2ActionPerformed
        supplyQuanty.setText("");
        Supplierrid1.setText("");
        Supplierrid.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_menuHelp2ActionPerformed

        
        
            
           

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Supplierrid;
    private javax.swing.JTextField Supplierrid1;
    private javax.swing.JTextField categoryidField;
    private javax.swing.JLabel categoryidLabel;
    private javax.swing.JButton dataBase;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField email;
    private javax.swing.JButton emailbtn;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private java.util.List<guiass2antoinettebolger.Products> list;
    private javax.swing.JButton logoutHelp;
    private javax.swing.JButton logoutHelp1;
    private javax.swing.JButton logoutMenu;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton menuHelp;
    private javax.swing.JButton menuHelp1;
    private javax.swing.JButton menuHelp2;
    private javax.swing.JTextArea message;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel productidLabel;
    private javax.swing.JTextField productnameField;
    private javax.swing.JLabel productnameLabel;
    private java.util.List<guiass2antoinettebolger.Products> productsList;
    private java.util.List<guiass2antoinettebolger.Products> productsList1;
    private java.util.List<guiass2antoinettebolger.Products> productsList2;
    private java.util.List<guiass2antoinettebolger.Products> productsList3;
    private javax.persistence.Query productsQuery;
    private javax.persistence.Query productsQuery1;
    private javax.persistence.Query productsQuery2;
    private javax.persistence.Query productsQuery3;
    private javax.swing.JTextField quantyField;
    private javax.swing.JLabel quantyLabel;
    private javax.persistence.Query query;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveButton1;
    private javax.swing.JTextField supplieridField;
    private javax.swing.JLabel supplieridLabel;
    private javax.swing.JLabel supplieridLabel2;
    private javax.swing.JLabel supplieridLabel3;
    private javax.swing.JLabel supplieridLabel4;
    private javax.swing.JTextField supplyQuanty;
    private javax.swing.JTabbedPane tpass2;
    private javax.swing.JTextField unitField;
    private javax.swing.JLabel unitLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMasterDetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMasterDetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMasterDetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMasterDetailForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new NewMasterDetailForm());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
            }
        });
    }
    
}
